db:
  username: postgres
  password: 123456
#  pool.size: 12
  driver: PostgresDriver
  url: jdbc:postgresql://localhost:5432/postgres
  hosts: localhost,127.0.0.1
#  spring.profiles.active: dev
  properties:
    first: 1
    last: 2
    key: value
  pool:
      size: 10
      timeout: 10
  pools:
    - size: 10
      timeout: 20
    - size: 20
      timeout: 30
    - size: 15
      timeout: 25

logging:
  level:
    root: WARN
    Pegas.pool.ConnectionPool: INFO
  file:
    name: log.txt
    path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springdata
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate

